function plotPercentNeuronsModulated(glmStructure)
%
% Plot the percentage of neurons that are modulated by time and/or movement velocity. 
%
% Input: 
%       glmStructure:       structure with p-values and slopes generated by GLME for each neuron
%
% Output: 
%       figure

    
    plotColors = {[0 102 204] ./ 255; [153 0 76] ./ 255; [204 153 255] ./ 255};
    
    rampingNeurons = find(cellfun(@(x) x < 0.05, {glmStructure.pTime}));
    motorNeurons = find(cellfun(@(x) x < 0.05, {glmStructure.pVelocity}));
    rampAndMotorNeurons = intersect(rampingNeurons, motorNeurons);
    
    hold on;
    b = bar(1:3, ([length(rampingNeurons), length(motorNeurons), length(rampAndMotorNeurons)] ./ length(glmStructure))*100);
    b.FaceColor = 'flat';
    b.EdgeColor = 'none';
    for iBar = 1 : 3
        b.CData(iBar,:) = plotColors{iBar};
    end
    ylabel('Modulated (%)');
    xticks(1 : 3);
    xticklabels({'Time', 'Velocity', 'Both'});
    %set(gca, 'FontSize', 14);
